"""Make media_type nullable

Revision ID: 0adeb6494274
Revises: f8e5c60d6d7c
Create Date: 2025-10-05 17:50:45.936151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0adeb6494274'
down_revision: Union[str, Sequence[str], None] = 'f8e5c60d6d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'media_type',
               existing_type=postgresql.ENUM('image', 'audio', name='mediatype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'media_type',
               existing_type=postgresql.ENUM('image', 'audio', name='mediatype'),
               nullable=False)
    # ### end Alembic commands ###
