"""Add 'document' value to mediatype enum

Revision ID: f5fcb6b173ec
Revises: 2a27d273b48c
Create Date: 2025-10-07 13:28:52.692610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5fcb6b173ec'
down_revision: Union[str, Sequence[str], None] = '2a27d273b48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE mediatype ADD VALUE 'document';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
